In [1]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# numpy dizileri

In [4]:
import numpy as np # --> as np np olaral demek

# numpy array

In [5]:
my_list = [10,20,30,40]

In [6]:
type(my_list)

list

In [7]:
np.array(my_list)

array([10, 20, 30, 40])

In [8]:
my_numpy_array = np.array(my_list)

In [9]:
my_numpy_array


array([10, 20, 30, 40])

In [10]:
type(my_numpy_array)

numpy.ndarray

In [11]:
my_numpy_array[0]

10

In [12]:
my_numpy_array[-2]

30

In [13]:
my_numpy_array.max()

40

In [14]:
my_numpy_array[1] = 100

In [15]:
my_numpy_array.mean()

45.0

In [16]:
# matris kolon ve sıraların olduğu dizeler

In [17]:
# matris özelikleri shape = şekil row by colum 

In [18]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1]]

In [19]:
numpy_matrix_list = np.array(matrix_list)

In [20]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
numpy_matrix_list.shape

(3, 3)

# numpy random


In [22]:
list(range(1,5))

[1, 2, 3, 4]

In [24]:
#arange --> numpy kodu

In [25]:
np.arange(1,10) # -->  numpy dzizsi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,45,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# linsapce --> eşit aralıklara artan bir dizi oluşturur

In [33]:
np.linspace(0 , 10 , 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [34]:
np.linspace(0 ,20,100 )

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [35]:
# random 

In [36]:
np.random.randint(1,20)

10

In [37]:
np.random.randint(10,20,40)

array([11, 15, 17, 14, 11, 12, 17, 18, 13, 11, 19, 14, 12, 18, 11, 19, 11,
       14, 14, 11, 11, 10, 16, 19, 18, 11, 19, 18, 16, 18, 18, 14, 10, 12,
       17, 10, 14, 18, 15, 13])

In [38]:
# numpy arrays methods

In [39]:
my_np_aray = np.arange(1,20)

In [40]:
my_numpy_array[2]

30

In [41]:
my_np_aray[2]

3

In [42]:
my_np_aray[1:17:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [43]:
my_list1 = list(range(1,20))

In [45]:
#my_list1[4:15] = 30 normal listeler buna izn vermez 

In [46]:
my_np_aray[3:13] = 40

In [47]:
my_np_aray

array([ 1,  2,  3, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 14, 15, 16, 17,
       18, 19])

In [48]:
other_array = np.arange(1,30)

In [49]:
other_sliceingList = other_array[2:22]

In [50]:
other_sliceingList

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [51]:
other_sliceingList[:] = 100

In [52]:
other_sliceingList

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [53]:
other_array

array([  1,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100,  23,  24,  25,  26,
        27,  28,  29])

In [54]:
numpy_list2 = np.arange(1,8)

In [55]:
numpy_list2

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
numpy_list2_copy = numpy_list2.copy()

In [58]:
numpy_list2_copy

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
# numpy operations with numpy arrays

In [65]:
new_array1 = np.random.randint(1,200,50)

In [66]:
new_array1

array([ 95,   6, 139, 141,   7,  80, 173, 197,  52, 131,  35, 196, 147,
        31,  16, 102,  53,  31, 199, 104, 148, 176,  24,  48, 170, 124,
        24, 177,  87,  56, 193, 179, 162, 156, 156,  97, 129, 198,  14,
        68, 104,  54, 154,   7,  41, 149,  82,  52, 175,  53])

In [67]:
new_array1 > 50

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True])

In [68]:
new_array1[new_array1 > 50] 

array([ 95, 139, 141,  80, 173, 197,  52, 131, 196, 147, 102,  53, 199,
       104, 148, 176, 170, 124, 177,  87,  56, 193, 179, 162, 156, 156,
        97, 129, 198,  68, 104,  54, 154, 149,  82,  52, 175,  53])

In [69]:
new_array1.mean()

103.84

In [70]:
lastArray = np.arange(1,200)

In [71]:
lastArray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [72]:
lastArray * lastArray

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664,
       11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689,
       13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876,
       16129, 16384,

In [73]:
lastArray / lastArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
lastArray - lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [75]:
lastArray.max()

199

In [76]:
np.max(lastArray)

199

In [77]:
np.sqrt(lastArray)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558,
        5.56776436,  5.65685425,  5.74456265,  5.83095189,  5.91607978,
        6.        ,  6.08276253,  6.164414  ,  6.244998  ,  6.32455532,
        6.40312424,  6.4807407 ,  6.55743852,  6.63324958,  6.70820393,
        6.78232998,  6.8556546 ,  6.92820323,  7.        ,  7.07106781,
        7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849,
        7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669,
        7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775,
        8.1240384 ,  8.18535277,  8.24621125,  8.30662386,  8.36